name: Hello World CI

on: [push] # This action runs on every push to the repository

jobs:
  build:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # This step checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

    - name: Print Hello World
      run: echo "Hello World!" # This command will simply print "Hello World!" to the console
