name: Hello World CI

on:
  push:
    branches:
      - "1-explore"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 
    - name: Print Hello World
      run: echo "approve 1-explore branch" 
