name: Go Test With Matrix 

on:
  push:
    branches:
      - "3-matrix"

  workflow_dispatch:

jobs:
 test:
    name: Test on Go ${{ matrix.go-version}} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.24']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' 

      - name: Install dependencies
        run: go get .

      - name: Test with Go
        run: go test -json > TestResults-${{ matrix.go-version }}.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
